### ISSUE TITLE
Enterprise version

### ISSUE THREAD

**Issue by vlm---** [Georgy-Losenkov/vsix-regex-editor-2019#4]
Hello, I really love this extension, been using it for my personal projects on Community edition. But at work I can't. Is there any particular reason for not supporting Enterprise version of Visual Studio?

**Comment by Georgy-Losenkov** [comment]
When I created that extension I did not have any issues related to Enterprise edition.
So I just added Enterprise edition explicitly into installation targets.
Also I published clone of the extension for Visual Studio 2022
