### ISSUE TITLE
Visual Studio 2022 Support

### ISSUE THREAD

**Issue by scottkuhl** [Georgy-Losenkov/vsix-regex-editor-2019#5]
### Installed product versions
- Visual Studio: 2022 All Versions

### Description
Make the extension available in Visual Studio 2022.

### Steps to recreate
1. Download the extension installer.
2. Run the installer.

### Current behavior
Message that it is already installed to all applicable products appears even though it is not installed in Visual Studio 2022.
It is also not listed in Online Extensions in Manage Extensions Visual Studio 2022.

### Expected behavior
Installs and works in Visual Studio 2022.

_Note: Sorry for the all the extra details.  I probably could have stopped with the title on this one._

**Comment by scottkuhl** [comment]
- [Writing Visual Studio Extensions with Mads - 64bit extensions for Visual Studio 2022](https://www.youtube.com/watch?v=L8b3kFriwCs)
- [Writing Visual Studio Extensions with Mads - Splitting extensions for Visual Studio 2022](https://www.youtube.com/watch?v=-PKIPTW6km0)

**Comment by Georgy-Losenkov** [comment]
Thank you, for information.
I totally missed first preview of Visual Studio 2022.

**Comment by ymg2006** [comment]
I made a pull request for this, please approve. Thanks

**Comment by DotNetWorker** [comment]
@ymg2006  Thanks so much, was about to do the same.

**Comment by ymg2006** [comment]
Please create a separate plug-in and release in vs market since I have updated all Nuget packages and adopted some changes for vs 2022. As far as I tested in new vs, it is working as it should.

**Comment by DotNetWorker** [comment]
> Please create a separate plug-in and release in vs market since I have updated all Nuget packages and adopted some changes for vs 2022. As far as I tested in new vs, it is working as it should.

@ymg2006 I've also installed your version to VS2022 and it looks to run ok, however... 
https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022
Gives a good guide to migrating to 2022, note section on "Use shared projects for multi-targeting" for supporting both old and new versions, this is well worth considering.

**Comment by Georgy-Losenkov** [comment]
Will do that soon.
All preparations have been done for 2022 RC, but I was quite busy last two weeks and did not have chance to create extension for 2022.

**Comment by Georgy-Losenkov** [comment]
Published clone of the extension for Visual Studio 2022.
For simplicity I put code into separate branch because adding 3 shared projects and adding 3 projects for Visual Studio 2022 in the case of the rarely modified code is too complicated
